project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wostrie2
      - icon: twitter
        href: https://twitter.com/WilliamOstrieII
format:
  html:
    theme: darkly
    css: styles.css



